### ISSUE TITLE
Mesh Placement with GDAL

### ISSUE THREAD

**Issue by comlor** [domlysz/BlenderGIS#100]
I am having an issue with where the mesh is being imported.  With most of the other DEM's I have imported, the origin is the center of the mesh.  This particular mesh, same projection CRS as the others, is not being placed at the origin.  The BlenderGIS georeference pane shows the correct values for center of image compared to GDALInfo.   I have a picture showing the Scene Georeferencing, The mesh with (CrossHairs in Blender at 0,0), gdalinfo, as well as gdalsrsinfo to show my proj4 string used to georeference scene.
![alignment](https://user-images.githubusercontent.com/14832244/36805747-1095b968-1c73-11e8-86d7-633c94d2e855.png)

**Comment by domlysz** [comment]
Can you join me the DEM for testing it ?

**Comment by comlor** [comment]
Here is the DEM I am using ATM.  The accuracy of this dem is pretty low, so it does not give great quality ATM.

It will not allow me to put tif file here.  So I uploaded to a repo on github here:  https://github.com/comlor/blender

The file name is input.tif in root of repo.

**Comment by domlysz** [comment]
it's just because the left half of the raster is all nodata, below a screenshoot in qgis with nodata set to black

![selection_036](https://user-images.githubusercontent.com/5639024/36813124-6a105c16-1ccb-11e8-9ad7-69d8c4a1cdcf.jpg)

and the perspective view of the import in Blender, the nodata value is set to a very high negative value

![selection_037](https://user-images.githubusercontent.com/5639024/36813189-aa797972-1ccb-11e8-9e84-31ff8e50e75c.jpg)

**Comment by comlor** [comment]
OK.  didn't even think to load in QGIS to check on DEM.  Thank you very much
