### ISSUE TITLE
Cannot Import (Unsupported File Format)

### ISSUE THREAD

**Issue by isentropicpotato** [domlysz/BlenderGIS#106]
I've installed the add-on and can access the various new functions. However, when I go to import a raw DEM, I get an error that I cannot import because it is an unsupported file format. Using "import -> Georeferenced raster" my filtered (and supposedly supported) file formats are limited to .tif, .jpg, .jpeg, .png, and .bmp. Any advice on getting Blender to accept the new file types? 

(Should note that I am fairly new to Blender.)

**Comment by domlysz** [comment]
What is the file you trying to import? Be careful, as I can see these sample files are not all DEM dataset but RGB images. Also you must check what is the coordinate system (make sure planar units are the same as altitude unit).

Also there is a currently undocumented feature that help getting heightmap automatically:
- start basemap, navigate whatever you want
- press E key to export the map on a new plane mesh
- then press the Get SRTM button (with the new mesh selected) and you'll got the elevation

Otherwise I've attached 2 working sample files for testing tif import (DEM and associated map texture)

[samples.zip](https://github.com/domlysz/BlenderGIS/files/1886240/samples.zip)
