### ISSUE TITLE
Imported rasters incorrectly scaled

### ISSUE THREAD

**Issue by iblueyonder** [domlysz/BlenderGIS#108]
Another BGIS issue I'm having: when I attempt to import raster images - in this case, a geoTiff background image of a city I'm working on - the image is scaled tiny in Blender. The viewport georeferencing matches that of the image I'm importing (WGS84 latlon - EPSG:4326). The image should be approximately 2.75km wide, but the plane that it imports onto is only 1.4cm wide in Blender.

**Comment by domlysz** [comment]
Longitude latitude are in degrees not meters. Earth perimeter at equator is about 40000 km so one degree equals 40000km/360° = 111km that's why the raster is so small. You must reproject it into a projection system in meters before the import or if gdal is installed setup the scene coordinnate system expected as destination system. The choice of the system depends of what is commonly used in your country.
