### ISSUE TITLE
The osgeo folder is missing

### ISSUE THREAD

**Issue by Heryx** [domlysz/BlenderGIS#130]
Hi, 
I do not have the osgeo folder in `blender_install_folder\2.7x\python\lib\site-packages\osgeo\data\gdal`
but only numpy and requests. 

Does it work the same? how can I solve this problem?

**Comment by domlysz** [comment]
Are you trying to install GDAL ?

**Comment by Heryx** [comment]
Yes, I installed it...I followed the gdal installation guide

**Comment by domlysz** [comment]
Try to import gdal module in blender's python console like explained in the guide. If it fails then gdal is not correctly installed. If it not fails then gdal is installed and there must be an osgeo foldr somethere

**Comment by domlysz** [comment]
I close this issue because it seems to me you just tried to instal GDAL in the hope of solving your cache folder setup issue #46, which will not because GDAL is completly optional as explained in the install guide's [disclamer](https://github.com/domlysz/BlenderGIS/wiki/How-to-install-GDAL)

Please reopen if you really need to install GDAL for some advanced features
