### ISSUE TITLE
Importing land cover data into 3D scene

### ISSUE THREAD

**Issue by Annnilinn** [domlysz/BlenderGIS#135]
Hello!

I am trying to create a 3D scene  of a city (.obj format) using a DTM (raster), and buildings and land cover as shapefile. I have imported the DTM and use this object to place the land cover shapefiles on top of it. It seems to work with some shapefiles but once I import a larger one, it shows a strange overlap with the other classes. Normally, the land cover classes shuldn't overlap. Does anyone know the reason why it looks like the shapefiles are overlapping? I have attached an image of the situation. 

Thanks for the time taken in reading my issue!
-Angela

![blendergisissue](https://user-images.githubusercontent.com/44289554/47210551-d3c94080-d3c5-11e8-8a4b-22a05a5b41a2.jpg)

**Comment by domlysz** [comment]
Hi,

Can you please attach the shapefile that causing the issue ?

**Comment by Annnilinn** [comment]
Hi Domlysz, thanks for your reply, I have attached the built and shrub layers, I have realized that the same issue happens in the other layers where the polygons tend to be bigger.

**Comment by Annnilinn** [comment]
[2.zip](https://github.com/domlysz/BlenderGIS/files/2495940/2.zip)

**Comment by domlysz** [comment]
As I can see your data come from a raster to vector automatic conversion, and this process generated a huge polygons with lot of parts and holes.

Mesh in Blender is a very different data structure than shapefile, typically a mesh is composed only by triangles or quad. Several years ago Blender introduced polygons support (aka ngons), but internally ngons are defined with triangles, that's why there are some limitations to take in consideration.

- ngons does not support holes unless the hole is connected to the polygon boundary with at least 2 edges. Currently the shapefile importer does not performs any extra tessellation for dealing with holes and any hole will result on a new overlapping face.

- a too complex ngons cannot be properly triangulate and may result on various artefact like extra overlapping faces. That's the main issue in your case.

The only solution I can see is to split multipart to single part and then tessellate the polygons before the import in Blender. Also, I think your land cover grid will be more useful as scrubs density texture for particle system of trees objects. For buildings it will be better to import a well formed vector dataset.

**Comment by domlysz** [comment]
sorry for not answering, this topic appears to be a more general question about Blender use case.
