### ISSUE TITLE
Import GeoTiff as DEM texture results in flat plane

### ISSUE THREAD

**Issue by Tiiri** [domlysz/BlenderGIS#137]
I've been using the add-on some weeks now and had great results. Really amazing work! 
Thanks to the documentation and Google I got everything working.
But now I'm stuck and out off ideas.
I've made a GeoTiff-file from a .sosi file with QGIS. When I import it as 'As DEM texture' the plane is still flat regardless whether I apply it on a existing mesh or not. I also tried exporting .png and .tif with worldfile from QGIS but that doesn't work either. The tiff-file is opened by blender in Image Editor correctly. The generated filename_bgis is completely black.
I had problems with tiff-files before but then saving as .png in Photoshop solved the problem (probably due to compression of the tiff). Unfortunately that's not working here.
Any suggestions for me? Thanks in advance.

**Comment by domlysz** [comment]
can you please attach your tiff file?

**Comment by domlysz** [comment]
Thanks you for sharing the file. The datatype of this raster is float64 and it's currently not supported in Blender. You must downgrade the datatype to float32 using gdal translate (in command line or through a recent QGIS version). Float32 tiff is the best choice for using DEM dataset across Blender. Avoid any conversion to png because you will lose data precision.

**Comment by Tiiri** [comment]
Thanks for the fast answer. I already tried conversion to float32, because
it was mentioned somewhere. I'll try again tomorrow or on Monday and let
you know whether it worked.

Am Fr., 2. Nov. 2018, 21:02 hat domlysz <notifications@github.com>
geschrieben:

**Comment by Tiiri** [comment]
Thanks for testing my file in Float32.
It's still not working for me though.
I get this result and warnings:
![import_tiff_float32](https://user-images.githubusercontent.com/44700270/47954757-a7e9b580-df96-11e8-9394-26aba70a2682.jpg)

**Comment by domlysz** [comment]
I suggest you the following workflow:
- Press * to start basemaps
- Press G and go to Rafossen zoom 16
- Press echap to exit basemaps. Now your scene is georef in webmercator near your dataset
- Import the DEM with this setup :
![selection_001](https://user-images.githubusercontent.com/5639024/47955133-82a77800-df93-11e8-8ef4-f497e5a89ed8.jpg)

Do not work in WGS84 longitude/latitude (EPSG 4326) as explained in the [FAQ](https://github.com/domlysz/BlenderGIS/wiki/FAQ). Webmercator is not the best choice either because this system causes  horizontal distortion, ideally you must work in your national projection system and reproject your data before any import in Blender.

**Comment by Tiiri** [comment]
That works!
Thank you very much!
