### ISSUE TITLE
Why isn't there an option to Apply to existing mesh for RAWDEM?

### ISSUE THREAD

**Issue by oxcxsxixbxaxn** [domlysz/BlenderGIS#140]
"As DEM texture" doesn't show any surface detail in the elevation, but does work applying it to an existing mesh.  RAW DEM has all the details, but can only create a separate mesh.  How do I apply the detailed elevation to my basemap?  SRTM is a bit his and miss, usually miss.

![image](https://user-images.githubusercontent.com/9394156/49250235-42160f80-f416-11e8-8f62-103196286bb7.png)

**Comment by domlysz** [comment]
Importing as DEM texture setup 2 modifiers : subsurf + displacer. You will get more detail if you increase the subsurf level. For very large mesh, a second subsurf can be added.

The pupose of raw DEM import is to generate a new point for each pixel and then triangulate the point cloud. That's why it produce a new separate mesh. It's a very different approach than using the DEM image as texture (a new texture can be stetup to any mesh). Once the DEM mesh produced it possible to import a geoferenced basemap on it with the "On mesh" option.

**Comment by oxcxsxixbxaxn** [comment]
Thanks, that makes sense now that I see the modifiers.  needs 2 subsurfs to show the same level of detail but at the number of divisions needed, blender becomes unresponsive.
I will try using the "on mesh" option
