### ISSUE TITLE
Shapefile not properly imported

### ISSUE THREAD

**Issue by mholthausen** [domlysz/BlenderGIS#146]
When importing a Shapefile (Geometry: Polygon (Polygon25D)) with BlenderGIS (for Blender 2.8 Beta), the imported object contains a lot more vertices than the original shapefile. I have to remove double vertices with `bpy.ops.mesh.remove_doubles(threshold=0.001)` first, before I can apply Blender modifier, like **Decimate**. Is this behavior deliberated by the importer?

**Comment by domlysz** [comment]
Shapefile format does not store any topological information, it means two adjacents polygons cannot share the same vertex, in other words each feature has it's own set of vertices and each vertex belongs to only one feature. BlenderGIS respect by default this behaviour, but there is an option under preferences to auto-merge duplicates vertices.

**Comment by mholthausen** [comment]
But still more vertices are imported than removed through the `remove_doubles`..

**Comment by domlysz** [comment]
can you please attach the shapefile for testing it on mly side ?

**Comment by domlysz** [comment]
Here a simple example : 2 polygons create in QGIS, each polygon have 8 vertices and 3 snapped vertices to the adjacent polygon

![image](https://user-images.githubusercontent.com/5639024/53008837-88d63d00-343a-11e9-9b4d-edcfcc5fa5b8.png)

The import in Blender gives 2 faces and 16 vertices as expected

![image](https://user-images.githubusercontent.com/5639024/53009090-0437ee80-343b-11e9-9747-d79014d51220.png)

Same import with the remove double option enabled gives 2 faces and 13 vertices. As expected the 3 shared location with duplicate vertices are now merged, and we have 3 truly shared vertices instead of 6 non shared.
