### ISSUE TITLE
Too Large Extend!

### ISSUE THREAD

**Issue by Mephphisto** [domlysz/BlenderGIS#160]
Every time I tried to "Get SRTM" I get the Error "Too Large extend"!
Only if I choose a miniscule map part I can download SRTM Data but then this data is a Blurry greyscale texture.

Is it somehow possible to get reasonably large Map pieces (e.g. big enough for an island like Islay Farör etc. )

**Comment by domlysz** [comment]
BlenderGIS rely on various web service for directly grabbing data like srtm or openstreemap. These services are designed to easily pick up data at specified location not for downloading large amount of data. In the respect of these services policy, BlenderGIS limit requests to a maximum area of 400km². 

I realize that this limit is a bit too low, as SRTM's resolution is about 90m / pixel so 400km² represents only 223x334 pixels (20x20km). I think you can safely increase this limit to 200x200km for example by editing yourself the source code, here is [the line to edit](https://github.com/domlysz/BlenderGIS/blob/master/operators/io_get_srtm.py#L65). I will make an update in that way too.

If needed, both srtm or osm projects provide a better way to download large dataset. For example SRTM data (geotiff) can be dowloaded from [NASA Earthdata](https://earthdata.nasa.gov/), [USGS Earthexplorer](https://earthexplorer.usgs.gov/) or [CSI CGIAR](http://srtm.csi.cgiar.org/srtmdata/) (this last one is pretty easy to use). These geotiff files can then be imported directly with BlenderGIS.

But be warned, dealing with large dataset in Blender can be really frustrated because Blender is not designed to handle this king of large image. There are some downgraded resolution of SRTM [here](http://srtm.csi.cgiar.org/srtm-250-resolution/) that can be useful for very large map.

**Comment by Mephphisto** [comment]
Thx for the Awesome reply! 
Very Helpful!

**Comment by jsj2311** [comment]
> BlenderGIS rely on various web service for directly grabbing data like srtm or openstreemap. These services are designed to easily pick up data at specified location not for downloading large amount of data. In the respect of these services policy, BlenderGIS limit requests to a maximum area of 400km².
> 
> I realize that this limit is a bit too low, as SRTM's resolution is about 90m / pixel so 400km² represents only 223x334 pixels (20x20km). I think you can safely increase this limit to 200x200km for example by editing yourself the source code, here is [the line to edit](https://github.com/domlysz/BlenderGIS/blob/master/operators/io_get_srtm.py#L65). I will make an update in that way too.
> 


Hello domlysz, how do I extend the limit for OSM? the link to the line of code that should be edited does not open.
Thank you very much.

**Comment by bamumich** [comment]
@domlysz, seconding jsj2311's point here. Would you mind updating the link so we may edit. I'm hoping to edit a slightly bigger area.

**Comment by sp2150** [comment]
https://github.com/domlysz/BlenderGIS/blob/0c00bc361d05599467174b8721d4cfeb4c3db608/operators/io_import_osm.py#L655
