### ISSUE TITLE
No texture mapped on the mesh? - Blender 2.8

### ISSUE THREAD

**Issue by taufikp** [domlysz/BlenderGIS#163]
Hi,

I have a weird problem.

Yesterday, the _first time_ I tried BlenderGIS, following the quick start guide, I can see the texture mapped onto the SRTM 3d mesh, (with all height/elevation glory on it), but today when I try to do the real mapping, all I see is this:

![BLENDERGIS_noTexture](https://user-images.githubusercontent.com/29309103/55201764-2faab780-51f7-11e9-9440-287f88955382.png)

The Google related mesh (and picture) are directly below the SRTM mesh, and in a much smaller size than the SRTM mesh. I remember that yesterday these meshes were exactly the same size: SRTM and Google meshes are matched in 1:1 fashion, and texture was beautifully mapped on the SRTM surface.

I tried to delete the google map cache and redo the steps in quickstart guide, with no luck.

What did I do wrong?

**Comment by domlysz** [comment]
Hi,

It's because SRTM operator works in 2 fashion ways
1. if your are in top view with no selected object then it grab raw SRTM data for the top view's visible extent
2. if you have a mesh selected then it grab SRTM data only for the mesh extent and apply the deform on it 

There was an issue in the code : if your are in top view then the method 1 is chosen even if there was a selected mesh. It's now fixed !

Thanks for the report.
