### ISSUE TITLE
SRTM elev points are not saved - Blender28

### ISSUE THREAD

**Issue by taufikp** [domlysz/BlenderGIS#164]
Hi,

Everytime I save the .blend file without applying the modifiers, I lose SRTM elev data. Is this a bug or is this by design?

Step to produce:
- get map data
- get SRTM data
- save it without applying any modifier
- close Blender 2.8
- open Blender 2.8
- open the saved file
- and you'll see there are no elev data vertices on the mesh

After getting all the data needed and save the file:
![BLENDERGIS_noElevDataSaved](https://user-images.githubusercontent.com/29309103/55268642-5253d380-52be-11e9-88a7-b9e42149408f.png)

Opening the saved file:
![BLENDERGIS_noElevDataSaved2](https://user-images.githubusercontent.com/29309103/55268653-6d264800-52be-11e9-81bb-35afdce66f73.png)

**Comment by PayamT** [comment]
Convert it to a mesh object to keep the geometry. 


Sent from Yahoo Mail for iPhone


On Friday, March 29, 2019, 5:37 PM, Taufik Purnomosidi <notifications@github.com> wrote:


Hi,

Everytime I save the .blend file without applying the modifiers, I lose SRTM elev data. Is this a bug or is this by design?

Step to produce:
   
   - get map data
   - get SRTM data
   - save it without applying any modifier
   - close Blender 2.8
   - open Blender 2.8
   - open the saved file
   - and you'll see there are no elev data vertices on the mesh

After getting all the data needed and save the file:


Opening the saved file:

**Comment by taufikp** [comment]
> 
> Convert it to a mesh object to keep the geometry.  Sent from Yahoo Mail for iPhone
>

This is essentially the same as applying modifiers, isn't it?

I would like to be able to save my work without applying modifiers first, because sometimes during development I need to change the surface elevation (I'm currently modeling a racing circuit for a driving simulation software). And I'd like to keep all mesh deforming-related modifiers as long as possible.

That's why if the elevation data from SRTM through modifier can be kept in the .blend file, it would be fantastic.

**Comment by domlysz** [comment]
You must save your blend file before grabbing SRTM data because until the blend file is not saved, extra files are just putted into a temporary folder which is purged at Blender's session exit. If the blend file is saved then the addon can place these files into the same valid folder and there will not be purged.

Blend format can also handle image data into it (called packed files), the basemap image is not packed by default because the image must be rewritten at each map view update. But when the map is exported to a new textured mesh then the image can be packed, it why, in your case, the map texture is still visible. Unfortunately DEM dataset like SRTM cannot be packed because Blender can only pack image as PNG and this format is not suitable to handle elevation data (typically one band of 16 or 32bits while PNG is only 8 bits per channel).

**Comment by taufikp** [comment]
Understood! I'll try it soon. Thanks a lot!

**Comment by taufikp** [comment]
Hi @domlysz 

I can now confirm that with your advice the SRTM data are now saved inside the .blend file. Thanks a lot!

**Comment by domlysz** [comment]
> SRTM data are now saved inside the .blend file.

more precisely, SRTM data are now saved in the same folder than the .blend file, beside it. Be careful to correctly manage these externals resources needed by the blend file.
