### ISSUE TITLE
Best practice option to shift terrain assets to scene origin?

### ISSUE THREAD

**Issue by rossoe** [domlysz/BlenderGIS#176]
Good evening,

As you may remember I've been working on tiled terrains, which you resolved for me recently [here](https://github.com/domlysz/BlenderGIS/issues/172)

I now need the best approach to shift multiple tiles (same terrain) closer to **Scene origin** to avoid visual errors because my tiles are so far from origin - whilst maintaining the ability to import tiles to match CRS georeference.

I seem to have a few options:

An old [post](https://github.com/domlysz/BlenderGIS/issues/39) mentions using '**editable origin location**'
![image](https://user-images.githubusercontent.com/28996048/59292781-a2afc000-8c75-11e9-8f0d-2bd3303eb380.png)

Within **crs x** and **crs y** which appears to convert map projection to scene origin coords -
![image](https://user-images.githubusercontent.com/28996048/59292829-b824ea00-8c75-11e9-83c3-222e3af0f93a.png)

Or code that someone mentioned [here](https://blender.stackexchange.com/questions/140662/dividing-terrain-mesh-up-into-multiple-tiles-with-script-border-gap-issue/141095#141095) - 

> With all tiles selected, and bottom left hand corner active run this code in python console.
> 
> >>> v = C.object.location.copy()
> >>> for o in C.selected_objects:
> ...     o.location -= v

Please confirm which is the most appropriate? as I don't want to mess up the georeference connection - given I want to add additional data to the assets ie OSM building shapefiles etc.

Thank you for any help

**Comment by domlysz** [comment]
I think there is a misunderstanding here. In fact BlenderGIS already shift the imported data near the scene origin however it would be impossible to deal the raw projected coordinates. For example the French projection system had its origin at longitude 0° and latitude 0°. This point is more than 5 000 km from the south of France, furthermore the unit of this projection system is in meter so every location in France have an y coordinate upper to 5 000 000, a far to high value for a 3d software like Blender. To stay closer to the scene origin and keep track of the initial coordinates the idea is just to choose a nearest coordinate which will be represented by the origin of the scene, that's the purpose of the 2 custom properties crsx and crsy : the scene origin x=0, y=0 is treated by BlenderGIS as x=crsx and y=crsy. The values displayed in the scene georeferencing panel are exactly the same of crsx and crsy properties.

So if you encounter too large coordinates the issue is not related to the scene origin, it's just because you want to cover a too large extent while still using meters units. But in your case there should not be any issue at all because your tiles represent an extent of 10x10km and as far I can test there is no visual glitch when working with this extent. The first time you import data through BlenderGIS, the scene origin is defined at the center of the resulting mesh, so you must be careful to not perform successive imports of dataset distant from each other otherwise the origin of the scene will not be adapted to the last imports. It may be the source of your issue. In my case, the scene origin is located at the center of the first tile I have imported.

![image](https://user-images.githubusercontent.com/5639024/59307701-6729eb80-8c9f-11e9-99ce-91935e0fa4f5.png)

**Comment by rossoe** [comment]
Thank you for the extra detail, it's much appreciated.

That looks like you have imported using **WGS84 lation**:
![image](https://user-images.githubusercontent.com/28996048/59308407-e536c400-8c98-11e9-9b1d-6660e59a801f.png)

And indeed I can replicate scene origin being at center of first tile loaded:
![image](https://user-images.githubusercontent.com/28996048/59308570-3d6dc600-8c99-11e9-9dcf-398bd70bb5a9.png)

perhaps I am doing this wrongly but I'm setting my CRS to georeference original data in this case **59S**
![image](https://user-images.githubusercontent.com/28996048/59308646-7a39bd00-8c99-11e9-8378-1db8ab542c1e.png)
and at import of asc step as well:
![image](https://user-images.githubusercontent.com/28996048/59308719-9c333f80-8c99-11e9-881b-4a78f9dfc6fa.png)

So my scene origin is then far away:
![image](https://user-images.githubusercontent.com/28996048/59308849-faf8b900-8c99-11e9-99d4-ade2396f3a66.png)

I then get what appears to be some anomolies with Blenders grid rendering:
![image](https://user-images.githubusercontent.com/28996048/59308933-35625600-8c9a-11e9-84d2-878302b2b7b6.png)

Having continued to test last couple of hours, I discovered that ticking both buttons next to **Origin**, and copy pasting the figures from **Transform location** into **X** and **Y**
![image](https://user-images.githubusercontent.com/28996048/59309259-0dbfbd80-8c9b-11e9-8d3e-02b7d5489a20.png)

I can move my tiles back to scene origin
![image](https://user-images.githubusercontent.com/28996048/59309466-86bf1500-8c9b-11e9-958a-67fdc11b8763.png)

& grid anomolies are no longer an issue:
![image](https://user-images.githubusercontent.com/28996048/59309207-eb2da480-8c9a-11e9-868b-52c29ce20731.png)

most importantly I can still load things like OSM building data - I hope I am doing this the right way?

**Comment by domlysz** [comment]
ok I think I know what's wrong in your workflow. I've the felling that you set yourself the projection **and origin** of the scene before any import. But in fact you must not set the scene origin by yourself, the addon will do that for you at first import. Even setting the scene projection is not mandatory, the addon will also set this accordingly to the projection specified for the first imported dataset. 

If you set yourself the origin, 

![image](https://user-images.githubusercontent.com/5639024/59334214-4478f080-8cfa-11e9-9fbc-ef3c5e36d5c1.png)

then the addon will consider that the origin of the 3d scene corresponds to the coordinates 0,0 in the projected system. 

![image](https://user-images.githubusercontent.com/5639024/59334809-953d1900-8cfb-11e9-8d08-98eb161bbf4d.png)


If the scene origin is already set then the addon will take it into account for honoring georeferencing. So if the center of your dataset is 5000,5000 and the scene origin is 0,0 then the imported mesh will be at 5000,5000. But if the origin is set to 5000,5000 then the mesh will be placed at scene center, and following the same logic, if the origin is at 2000,2000 then the mesh will be placed at 3000,3000.

So by setting the origin to 0,0 before the import you lose the ability of the addon to work with geodata recentered near the scene origin. You must let the addon setting itseft the origin by computing the center of the first dataset you trying to import.

However, as you found, it's possible to edit the origin from the dedicated panel, the addon will automatically move all the objects accordingly, so setting the origin with a coordinates around the projected location of your data will shift all your objects near the scene origin. Note that it's not works if you set directly the custom properties crsx and crsy, the purpose of the georef panel is to add the ability to edit the origin without loosing georeferencing of previously imported objects. So finaly you doing it following the right way !

**Comment by rossoe** [comment]
Thanks - great to have such detailed clarification
