### ISSUE TITLE
Georeferencing and wrong 3D cursor.

### ISSUE THREAD

**Issue by salmagro** [domlysz/BlenderGIS#185]
I am having problems with the location of the model, according the coordinates shown in the 3D cursor. I am familiar with QGIS but new with GISBlender. I hope the community could guide me.

I am importing a MDT and OTF in the Coordinate system EPSG:31255, for creating a mesh. (The files have been assigned the same EPSG  in QGIS before importing.) 

![image](https://user-images.githubusercontent.com/52298571/63190471-90337780-c066-11e9-9edf-07fb7047ce85.png)
![image](https://user-images.githubusercontent.com/52298571/63210035-21e3c900-c0e9-11e9-957f-d3e079948878.png)

* The CRS is well assigned to the scene, and the "Geocordinates" showed in the down-left corner are correct. 
![image](https://user-images.githubusercontent.com/52298571/63190685-00da9400-c067-11e9-8c93-705295fb5189.png)
![image](https://user-images.githubusercontent.com/52298571/63190712-1223a080-c067-11e9-9b12-ffb67da5daa3.png)

 * But the model is located in the origin of the scene according to the values of X, Y, Z in the 3D Cursor window.
![image](https://user-images.githubusercontent.com/52298571/63190890-78a8be80-c067-11e9-9af7-90c4489c97e6.png)
![image](https://user-images.githubusercontent.com/52298571/63190900-81999000-c067-11e9-85e9-bc840bfc12f8.png)

I need my model **inserted in the location of its coordinates**, and not in the origin. How this task could be done?

Thanks in advance.

**Comment by domlysz** [comment]
Hi,

Please read the doc : https://github.com/domlysz/BlenderGIS/wiki/Georeferencing-management

**Comment by salmagro** [comment]
Thank you very much for your response. 
I've read it, before creating this issue. It explain why the mesh in the origin, but still I don't know how to translate the mesh in that way that the 3D cursor shows the coordinates.

> Hi,
> 
> Please read the doc : https://github.com/domlysz/BlenderGIS/wiki/Georeferencing-management

**Comment by domlysz** [comment]
You can directly edit the coordinate of the scene origin through the geoscene panel, all objects will be automatically shifted accordingly

![image](https://user-images.githubusercontent.com/5639024/63209689-881a1d00-c0e4-11e9-9cd5-bb72e93384a6.png)

But as explained in the doc it's not a good idea because you may encounter various visual glitch or 3d navigation issues. For example in your case, Blender will not able to differentiate in a non ambiguous way vertices that are distant less than 0.1 meters in y axis because coordinates have only 7 significant digits of precision.

**Comment by salmagro** [comment]
I really appreciate your help, thanks for the explanation.
