### ISSUE TITLE
Zoom to mouse position breaks alignement of 3D data and basemap if not over (0,0,0)

### ISSUE THREAD

**Issue by mirlip** [domlysz/BlenderGIS#21]
When zooming in the viewport after aligning the 3D datas and the basemaps, the alignment is lost. It looks like the basemap is being zoomed to mouse position, but not the 3D view, which is zoomed toward 0,0,0. (even when zoom to mouse position is activated in the Blender's user prefs)
Zooming when the mouse is over 0,0,0 works great.

**Comment by domlysz** [comment]
Yeah know that, It's because Basemaps always update scene origin coords when panning or zooming to mouse. It's important to update scene origin coordinates because you really don't want to zoom somewhere in US and have your scene origin stay back somewhere in Europe, with units in meters it's just impossible for Blender to correctly handle this situation.

I've already planned to add an option to move objects location according to scene origin updates. Remember Basemaps is really not finished and not well integrated with others BenderGIS tools but I really appreciate your feedback.

**Comment by mirlip** [comment]
Wouldn't that be enough to let Blender's "zoom to mouse position" enabled? It seems that the basemap mode force disable it.

**Comment by domlysz** [comment]
Basemaps has it own _zoom to mouse_ option, independent from the Blender's 3dview one.  When zooming or panning in the maps there isn't 3d view move (except for the height), it's just the background image which change. As I've described above, it's not conceivable to truly move 3d view because if you start in US and got to Europe your scene origin will be exceedingly far away from your actual position

Actually a workaround is to disable _zoom to mouse_ option (from Basemap addon) and avoid any panning, so the data stay aligned

**Comment by mirlip** [comment]
Ok, I understand. But I think both possibilities (Basemap's zoom to mouse position and Blender's zoom to mouse position) can make sense depending on the use case. I use it to get details on small areas (a town and it's surrounding). In this case, their is no precision problem triggered by tiles being too far away from origin. So maybe changing the zoom to mouse position to have 'deactivated', 'basemap only' and 'blender's zoom' ? With some warning for Blender's zoom that user must stay in a reasonable area.
Blender's zoom already work after pressing escape, it just needs automatically updated tiles.

**Comment by domlysz** [comment]
you're right it can be an useful option. There are lot of things remaining to do to improve basemaps addon !

**Comment by domlysz** [comment]
Fixed in latest update (moving objects according to new origin).

I've created another issue about an option for moving 3d view instead of origin
https://github.com/domlysz/BlenderGIS/issues/25

**Comment by mirlip** [comment]
Thank you for working on it and proposing a solution in the meantime :)
