### ISSUE TITLE
Blender Crashes when trying to edit imported shp-file that contains Vector(Area) format

### ISSUE THREAD

**Issue by pixeltumbler** [domlysz/BlenderGIS#264]
**Blender and OS versions**
Blender 2.82
Windows 10
**Describe the bug**
When trying to edit (going to edit-mode with the object selected) an imported
shp file Blender crashes. This only happend when the data was in Vector (Area)
when I tried it with Vector(line) it worked. 

**Error message**
Microsoft Windows [Version 10.0.18363.657]
(c) 2019 Microsoft Corporation. Med ensamrätt.

C:\Windows\System32>cd C:\Program Files\Blender Foundation\Blender 2.82

C:\Program Files\Blender Foundation\Blender 2.82>blender
Read prefs: C:\Users\Mats\AppData\Roaming\Blender Foundation\Blender\2.82\config\userpref.blend
found bundled python: C:\Program Files\Blender Foundation\Blender 2.82\2.82\python
Info: Deleted 1 object(s)

INFO:BlenderGIS-master.operators.io_import_shp:352:Read shapefile...
INFO:BlenderGIS-master.operators.io_import_shp:362:Feature type : Polygon
100%
INFO:BlenderGIS-master.operators.io_import_shp:732:Build in 1.122033 seconds
Error   : EXCEPTION_STACK_OVERFLOW

C:\Program Files\Blender Foundation\Blender 2.82>

**How to Reproduce**
I downloaded shp-files from https://www.diva-gis.org/gdata
I choose italy and administrative areas. As you can see the 
website states that the data is vector (Area)
I started blender 2.82 as default cube and used blender GIS downloaded today (2020-02-16)
![blenderGisShpImport1](https://user-images.githubusercontent.com/59435159/74597499-a98e9e00-5060-11ea-8c31-9c088ebb3abe.png)
Choose the file ITA_adm0.shp (I zipped the file since I couldnt upload it as is. )
[ITA_adm0.zip](https://github.com/domlysz/BlenderGIS/files/4209224/ITA_adm0.zip)
![blenderGisShpImport2](https://user-images.githubusercontent.com/59435159/74597521-1a35ba80-5061-11ea-98a6-cc7f5f979554.png)
I left the settings as in this image
![blenderGisShpImport3](https://user-images.githubusercontent.com/59435159/74597525-2b7ec700-5061-11ea-88c9-c61104c4b476.png)
I removed the default cube.
![blenderGisShpImport4](https://user-images.githubusercontent.com/59435159/74597532-39cce300-5061-11ea-9733-b6534efaba4c.png)
I selected the object and choose edit-mode and Blender crashed. 
![blenderGisShpImport5](https://user-images.githubusercontent.com/59435159/74597540-59640b80-5061-11ea-888d-bc96d3a601a3.png)

**Comment by domlysz** [comment]
Works for me, but I suspect the issue come from the fact that the data use geographic coordinates in degrees. As 1 degree one earth is about 111km, the resulting mesh is very small. 
Furthermore, in Blender coordinates have only 7 significant digits of precision, so as one meter equal about 0.00001° it's impossible to reach a submetric precision using data coordinates in longitude/latitude. Blender will not be able to strongly differentiate points too close each others which can cause crashes due to a corrupted mesh geometry.

So, [as explained in the FAQ](https://github.com/domlysz/BlenderGIS/wiki/FAQ#why-after-the-import-of-my-data-the-resulting-mesh-is-extremely-small-on-x-and-y-axis-but-seems-correct-on-z-axis-), you must use another projection system.

**Comment by pixeltumbler** [comment]
No worries, thanks for the response. Just figured I would report the bug. 
No biggie, as this only happend with adm0 (the one with the least amount of detail), 
I could just go one level deeper at adm1 and connect the different areas.

**Comment by domlysz** [comment]
ok greats
