### ISSUE TITLE
shape file are too small after import

### ISSUE THREAD

**Issue by mirlip** [domlysz/BlenderGIS#27]
Hi Domlysz,
When I import one of the files included in http://download.geofabrik.de/europe/germany/baden-wuerttemberg/freiburg-regbez-latest.shp.zip , although I added the epsg code you gave in the dxf thread in user prefs and I used it on import, it is too small (the whole region is smaller than the default cube). When I import the SHP after importing the DXF it works like a charm.
The console output:
```
Read shapefile...
Feature type : PolyLine
0%, 10%, 20%, 30%, 40%, 50%, 60%, 70%, 80%, 90%, 100%
Imported mesh had some problem, check the result!
PyContext 'window' not found
PyContext 'window' not found
PyContext 'scene' not found
PyContext 'screen' not found
PyContext 'screen' not found
PyContext 'gpencil_data' not found
PyContext 'screen' not found
PyContext 'screen' not found
PyContext 'edit_object' not found
PyContext 'screen' not found
PyContext 'screen' not found
PyContext 'window' not found
```

**Comment by domlysz** [comment]
Remember your file is in wgs84 latlon, it means the coordinates are in degrees. One degree on the earth is equals to approx 111km so one meter is approx 0.00001 degrees ... and the scale is correct.

As I already say, working in degrees is really a bad idea, we need reliable map projection.

Please read carefully the [wiki](https://github.com/domlysz/BlenderGIS/wiki/Gereferencing-management) all is already explained :

**Reprojection will be involved each time a coordinate or a dataset must be transformed to match the scene CRS.**

When you import a shp, if the scene is not already set then there is no reprojection and your data stay in degrees. But if you set the crs before trying to import then there will be a reprojection (and when you import a dxf you also set the scene crs ...). thats all


and furthermore ...

*So, because the scene CRS leads all reprojection tasks, it must be carefully choosen to minimize transformation requests as much as possible. It's a good idea to harmonize your data to the same CRS through a dedicated software like QGIS before trying to import them in Blender.*

**Comment by domlysz** [comment]
so in summary

Step 1: add a new predefinate crs

![selection_016](https://cloud.githubusercontent.com/assets/5639024/16125633/d2f35c36-33f4-11e6-83d1-b4e9aa5c14b6.jpg)

Step 2 : set the scene crs

![selection_017](https://cloud.githubusercontent.com/assets/5639024/16125647/dd0f5a76-33f4-11e6-85be-48387ccffb9b.jpg)
![selection_018](https://cloud.githubusercontent.com/assets/5639024/16125648/dd12a5b4-33f4-11e6-9572-d8324f66d2e2.jpg)

Step 3 import the shp

![selection_019](https://cloud.githubusercontent.com/assets/5639024/16125660/e8361e62-33f4-11e6-92c3-cc98a51ac300.jpg)

**Comment by mirlip** [comment]
Thanks a lot for this steps, it works :) This step by step tutorial is perfect for the wiki actually.

**Comment by mirlip** [comment]
And now I know why other shape files import with the right size directly, they have their projection already applied and specified in the shape file. The shape files from geofabrik are cool, but don't have any projection nor information about the projection they need Id I'm correct.

**Comment by domlysz** [comment]
shp from geofabrik are in longitude latitude because osm data cover all the world and lonlat is the most universal way to represent coordinates on the earth, it's the best choice they could make.

Each user must choose the right map projection depending on the location of the data they pick up from osm. Each country have its own set of commonly used projections, you just need to identify what are these projections and after, it will be always the same (unless you work in another country)

And remember you can identify the current projection of a shapefile by opening the *.prj file in a text editor, or just opening the *.shp in QGIS and look at layer properties

**Comment by mirlip** [comment]
Thank you for the tip regarding the .prj file :)

**Comment by mirlip** [comment]
Just a small clarification suggestion: I would name the first CRS "original CRS" or "file CRS" and the second one "target CRS" or "reprojection CRS".
Adding an option to add a target CRS in the import window would also help a lot to save some steps.
