### ISSUE TITLE
General topic : discussion, help, suggestions

### ISSUE THREAD

**Issue by domlysz** [domlysz/BlenderGIS#29]
Just talk about BlenderGIS !

**Comment by mirlip** [comment]
Suggestion from the shp import thread: naming the first CRS "original CRS" or "file CRS" and the second one "target CRS" or "reprojection CRS" would help understand what everyone of them do easily.
Adding an option to add a target CRS in the import window would also help a lot to save some steps and would help newcomers to find this function intuitively.

**Comment by domlysz** [comment]
Hi mirlip


I'm sorry I rewrote your modification on the wiki because it does not fit well what I had planned for this part. I hope you're not upset, I was thinking you just want add info about GDAL_DATA

I've disable contributors on the wiki, not because I don't want any contributor (on the contrary I really encourage this), but I prefer the pull request model which allows review and discussions before publish modification. Unfortunately as I see it seems a little complicated to use this schema in github

http://stackoverflow.com/questions/10642928/how-to-pull-request-a-wiki-page-on-github

will investigate this

see ya

**Comment by mirlip** [comment]
Hi Domlysz,

So much to do at the moment, I'm happy if you do it, no offense taken, don't worry. I tried my best, but it's always hard to make it look like if it was one person writing. I may have more time in a month. Then I can come back to you so that I can hopefully better help you. In the mean time, I hope my beta-testing and suggestion help

see ya

**Comment by mirlip** [comment]
Finally some free time again to test BlenderGIS :) It made huge steps in usability and the new UI looks really good. The only thing that I would keep as an option (disabled by default) would be to change the grid size. It makes zooming difficult and for someone not knowing Blender, it will be very disturbing to not be able to zoom in anymore. (it happens when you select your project location in the default scene by just zooming with the basemap operator.)
Other notes for the doc: 
- deleting the "python" folder under linux also allows to use the system python with daily builds. 
- On Ubuntu 16.04, the default repositories have the right GDAL version and bindings, so no need for the ppa.

**Comment by bvgnt** [comment]
Auto extrude buildings.

Could it be possible to automate building extrusion from contour.

- Get building contour from OSM
- Shrinkwrap it to the TIN surface
- Create a centroid for each building
- Calculate altitude difference between terrain model and surface model for each centroid
It looks like both data are often given and used to get building altitudes.
- Extrude according to each value

Auto roads ... ;)
Auto trees ;) ;) ;)

**Comment by mirlip** [comment]
Hi domlysz,
How are you? Hope everything is fine :)
Regards

**Comment by domlysz** [comment]
Hi mirlip, thanks for the message and sorry for not responding earlier. I'm fine, just starting a new job since september so unfortunately I didn't have much time for working on BlenderGIS, but stay tunned for 2017 !

**Comment by mirlip** [comment]
Congratulation for your new job. I will stay tuned :) Have fun and take care.

**Comment by pyarchinit** [comment]
I think your blenderGIS can be the bridge between Blender and Geodatabase such as Spatialite or Postgis. We have developped a plugin for QGis which stores data into geodatabase and creates wiev joining spatial data with alphanumerical data, to create 2D maps interactively through specific queries. Here there is an example: [from pyarchinit to blenderGis](https://www.youtube.com/watch?v=s8uaLqk9aDY). But now we need to pass from postgres or spatialite to shapefile to import data into blender through blenderGIS. Do you think is possible create an import system from postgis or spatialite as you do from shapefiles? You can project QGis and Osgeo into Blender World. Best regards. Luca

**Comment by kikislater** [comment]
Problem with blender is you have to shift huge coordinates to 0. Otherwise you could have a big shift in modified data and a slow process time.

There was an attempt to connect postgis database to blender here in 2010 : http://www.isprs.org/proceedings/XXXVIII/4_8_2-W9/papers/final_138_138_scianna.pdf

Python scripts seems not available nowaday but may be I have them.

For a far away better integration, cgal and pdal should be a must have

**Comment by neon-ninja** [comment]
Hi @domlysz!

Firstly, thank you so much for this awesome plugin! It's saved me a lot of time.

I'm starting a new project, where I have a collection of shapefiles describing the flow of lava in a simulated volcanic eruption. Each shapefile describes the lava extent in 2D on a given day. What I'll need to do is interpolate between each of the shapefiles to create an animation of lava over time. I'm familiar with python / the blender python API, and am planning on writing a script to create shape keys for each shapefile. As each shapefile has a different number of vertices the script will also have to find the maximum vertex count and normalise all shapefiles into the same number of vertices for shape keys to work.
Would such a script be useful to others? Would it be worth creating a PR once I have the script in a stable state?
Do you have any advice for me? Do you know of anything that might be useful for this task?

Cheers,
Nick
