### ISSUE TITLE
Advice for importing a shapefile as a curve

### ISSUE THREAD

**Issue by mpickering** [domlysz/BlenderGIS#293]
I am importing a shapefile containing a single line using `Import -> Shapefile` which imports a shapefile as a mesh. 

It is possible to convert this mesh into a curve using `Object -> Convert to -> Curve from Mesh` but this doesn't produce good results because the mesh contains overlapping points. The resulting polyline is disconnected. You can try and clean-up the mesh first by using `Mesh -> Cleanup -> Merge by Distance` which works well for simple lines but more complicated overlapping lines remain disconnected. 

Do you have some advice about how to overcome this problem?

Would I be best directly creating the curve myself from the contents of the shapefile using a python script for instance?

**Comment by mpickering** [comment]
I have also tried the `Merge duplicate vertices` preference which still leads to a disconnected curve.

**Comment by domlysz** [comment]
possible to attach the shp ?

**Comment by mpickering** [comment]
@domlysz Please find attached the shapefile ([route.zip](https://github.com/domlysz/BlenderGIS/files/4344316/route.zip))

**Comment by domlysz** [comment]
I think you just need to reproject you shp in a metric projection system because working in longitude/latitude coordinates is problematic in Blender. For example, in my script the distance for merging duplicate is set to 0.0001 units, so if you work in degrees this value will represents approx 11 meters. 

See FAQ :
https://github.com/domlysz/BlenderGIS/wiki/FAQ#why-after-the-import-of-my-data-the-resulting-mesh-is-extremely-small-on-x-and-y-axis-but-seems-correct-on-z-axis-

**Comment by mpickering** [comment]
Have you considered trying to mitigate this in BlenderGIS? Perhaps by reprojecting everything to Mercator (3857) internally? 

I will try using 3857 myself by translating the worldfile.

**Comment by domlysz** [comment]
Dealing with projection system is the responsability of the user because there are as many projection systems as countries. Most of the case 3857 is really not the best option ([FAQ again](https://github.com/domlysz/BlenderGIS/wiki/FAQ#why-my-measurements-on-basemaps-reference-seems-wrong-)). No one can predict the best projection system for each use case except the user itself. I know projections systems can be very confusing for non GIS-guy but its an essential property of geographic data. Hiding it would mean making a crucial choice for the user, without consulting him about the consequences of this choice.

**Comment by mpickering** [comment]
Using a metres projection does fix the issue (3857), I will also try 27700 but this level of precision it not very important for me. 

Thanks for your help.
