### ISSUE TITLE
Get SRTM - Runtime Error: Unable to open raster

### ISSUE THREAD

**Issue by lacples** [domlysz/BlenderGIS#300]
# **Blender and OS versions**

 

# **Describe the bug**

# **How to Reproduce**

# **Error message**

**Comment by sky2lz** [comment]
Blender 2.82 in Windows 10 OS 

while trying to get SRTM data the error log shows Unable to Open raster . Check logs for more info 

Add in a cube followed by adding a basemap from Web GeoData , works fine upto this point but when clicking get SRTM for that particular location (i tried New York City and  Mount Wilder) shows the error (attached Screenshot)
![Screenshot (99)](https://user-images.githubusercontent.com/43520828/77134444-0381e980-6a8d-11ea-88a0-4cfdf3e8ef29.png)

**Comment by Zeiram3f** [comment]
Yup. I'm getting the exact same error. I tested this on 2.82 and 2.80. Disabled my firewall as well, just to see if that had any effect. Null. I'll standby for an update as to what's happening here.

**Comment by domlysz** [comment]
From the wiki : https://github.com/domlysz/BlenderGIS/wiki/SRTM

> The Get SRTM  operator rely on third party web services that provides API to request SRTM data. Taking this into consideration, this function can be broken at any time (server closed, in maintenance or overloaded). It also rely on your internet connexion and can fails due to any network issue (no internet, instable connexion, proxy of firewall missconfiguration).

So, the service is down for the moment, it return a text file mentioning an error instead of SRTM data. HTTP status code return 200 which mean the request has succeeded, so the error cannot be caught, the script try to open the response but it's a text file not a raster datafile that's why it fails.

The returned text file error :

> Error: Error from GDAL: ERROR 4: `/data/raster/SRTM_GL3/SRTM_GL3_srtm.vrt' does not exist in the file system,and is not recognised as a supported dataset name.GDALOpen failed - 4`/data/raster/SRTM_GL3/SRTM_GL3_srtm.vrt' does not exist in the file system,and is not recognised as a supported dataset name. (Error Code: 1)

The service will likely be restored in the coming days. Meanwhile, as mentioned in the wiki, there is another provider for SRTM data, users can select it in the addon preferences if the first one fails.

![](https://raw.githubusercontent.com/wiki/domlysz/blenderGIS/Blender28x/images/srtm_providers.jpg)

**Comment by sky2lz** [comment]
Yes , it is working rightly now with OpenTopography and MarineGeo .

During that period of time however , i did try the Marine-geo server , it was not working either . 

You can close this issue now . thanks .

**Comment by eugene-source** [comment]
Hi there...
This has been a total nightmare for me guys. First i had to get blender to work due to a Open GL 3.3 error. Next Install BlenderGIS and after following all the rules, the SRTM data wont load. Please advice because i've followed the thread here but still dont know how. 
![error](https://user-images.githubusercontent.com/57793799/98008159-e7a13d00-1dfc-11eb-9fcc-4a34b788f335.png)

**Comment by ebo123654** [comment]
<img width="370" height="328" alt="Image" src="https://github.com/user-attachments/assets/e411f4f8-8759-4ff3-a5dc-55c04ac570be" /> mine s not showing the basemap how can i fix it
