### ISSUE TITLE
Basemap only shows gray tile

### ISSUE THREAD

**Issue by rickpalo** [domlysz/BlenderGIS#313]
# **Blender and OS versions**
Blender 2.82 (sub 7)
Windows 10

# **Describe the bug**

When selecting Basemap, the map displays as a gray square.  Exporting the map to a texture also creates the solid gray square.

# **How to Reproduce**
Select Basemap.
![selection](https://user-images.githubusercontent.com/38861886/78943053-3873d180-7a78-11ea-9496-cc07126a240f.png)

Gray square appears.  Map location, zoom, etc all appear, indicating the map should be displayed.
![square](https://user-images.githubusercontent.com/38861886/78943200-8be61f80-7a78-11ea-93b1-bf971a376cbd.png)

# **Error message**
The DEBUG log is attached.
[debug.log](https://github.com/domlysz/BlenderGIS/files/4458824/debug.log)

**Comment by Phyllise001** [comment]
I am the same kind of problem. How to solve it.

**Comment by w370534924** [comment]
same kind of problem.

**Comment by domlysz** [comment]
@rickpalo the issue is now solved ec9293ba7d11c740c91dc9dd09b2d5ba63785445, thanks for the report. However I suggest you to use the webmercator projection instead of WGS84, see [FAQ](https://github.com/domlysz/BlenderGIS/wiki/FAQ#why-after-the-import-of-my-data-the-resulting-mesh-is-extremely-small-on-x-and-y-axis-but-seems-correct-on-z-axis-) about coordinates in degrees

**Comment by rickpalo** [comment]
That works!  Thank you for looking at this so promptly!
