### ISSUE TITLE
applying DEM as modifier to raster plane - when using "fill nodata" it just freezes

### ISSUE THREAD

**Issue by derekeden** [domlysz/BlenderGIS#319]
Hello,

Thanks for developing this add on. It's insane. Saved me some serious grief and writing my own tools.

I am having one issue when trying to create my own textured DEM meshes.

Here are the steps I follow:

1. Import > Georeferenced Raster > Basemap on new plane
2. Specify Raster CRS (choose the right one, in my case UTM16N)
3. Import > Georeferenced Raster > DEM as displacement texture
4. Apply on existing mesh (choose mesh from steps 1/2)
5. Specify raster CRS (same as previous)
6. Fill nodata values

When I do this Blender just freezes. It's been about 20min but probably just going to kill it.

Oddly, when I do this without choosing "Fill nodata values" the process completes in the blink of an eye.

I have downsampled my original rasters to approximately 10MB each so the sizes are manageable.

They have the exact same extents and resoluton. DEM raster contains one band of elevation values.

They are approx. 3000 x 2000 pixels each.

See img of result when I don't fill nodata:

![image](https://user-images.githubusercontent.com/36650862/79826092-d3b65200-8368-11ea-8572-2b1a921da9d0.png)

If I cant get around this error of Blender freezing when I try to clip nodata values, can you suggest a work around?

I thought about just manually selecting and deleting the vertices with nodata values but I guess the displacement modifier works differently than I thought and doesnt actually turn the basemap into a mesh with vertices at the pixel locations.

I am pretty new to Blender so excuse my ignorance :D Possibly there is another way for me?

Appreciated your feedback.

**Comment by domlysz** [comment]
Hi,

By default the fill nodata option is very slow, I'm not surprising that it freeze Blender especially if there are larges areas of nodata. I say by default because if BlenderGIS works with the GDAL library then it will be more efficient. However installing GDAL across Blender can be really tricky so I suggest to you to just pre-process you DEM with GDAL beforehand. Here the documentation of the utility : https://gdal.org/programs/gdal_fillnodata.html, if you prefer using a graphical interface then go with QGIS it expose most of GDAL tools.

However fill nodata will just assign a value to nodata pixels by interpolation or extrapolation, so in you case you will get large flat area. Maybe the displacer is not the best option for dealing with this situation. **I suggest to import first the DEM with the option _Raw DEM_, this one will filter nodata values. Then import your aerial photo with the option _Basemap on mesh_. That's all !**

If you encounter slowness with the Raw DEM option you can try to uncheck the _build faces_ option,  because building faces with lot of nodata will slow down the calculation. Without this option it will import only a point cloud but you can easily recreate faces with the Delaunay triangulation tool which can be faster.

Hope it help

**Comment by derekeden** [comment]
Thanks for the prompt reponse. I am familiar with GDAL and QGIS so could likely process the DEM/img before hand.

I ended up just doing what you said, import the Raw DEM and using basemap on mesh to overlay the image. Worked like a charm though obviously slower because of the large number of pixels/vertices in the mesh.

**Comment by derekeden** [comment]
BTW again, great job on this add on. Very helpful. I am coming from an engineering background where GIS and georeferencing is everyday stuff, but am trying to work with Blender more for rendering model results.
