### ISSUE TITLE
Can't merge roads per vertex group

### ISSUE THREAD

**Issue by eobet** [domlysz/BlenderGIS#324]
# **Blender and OS versions**

2.82.7 on Windows 10

# **Describe the bug**

It seems that all highways imports as split edges, but grouped into vertex groups. I tried to merge each road together using that information, but the result of the script I made merges all vertices instead and I can’t figure out why.

# **How to Reproduce**

Run this script on any imported roads:

```python
import bpy

obj = bpy.context.object

# EDIT MODE
bpy.ops.object.mode_set(mode='EDIT', toggle=False)

# LOOP THROUGH ALL VERTEX GROUPS
for group in obj.vertex_groups:
    bpy.ops.mesh.select_all( action = 'DESELECT' )
    # SELECT VERTICES IN GROUP
    bpy.ops.object.vertex_group_set_active( group=str(group.name) )
    bpy.ops.object.vertex_group_select()
    #verts = [ v for v in obj.data.vertices if v.select ]
    # MERGE SELECTION BY DISTANCE
    bpy.ops.mesh.remove_doubles( threshold=0.1, use_unselected=False )

# OBJECT MODE
bpy.ops.object.mode_set(mode='OBJECT', toggle=False)
```

# **Error message**

Go into edit mode and select linked and you'll see that ALL roads are now linked.

I tried making objects myself, split them and assign vertex groups, and there my script works. Something in how this add-on imports and assigns roads to vertex groups prevents me from merging each road separately.

The reason I want to do this is I want to convert the roads to curves and put geometry on them.

**Comment by domlysz** [comment]
hi,

One vertex may belong several groups that's why your approach doesn't works. Vertex groups allows to keep track of OSM tags in Blender. A road can have many tags and a same tags can be used for many roads.

However I've made a quick update which I think solves your problem, now all vertices of the same road are correctly connected. 
3522605594fbe3f0cdcb00655163b4fe31a1c8d9

Do not forgot to uncheck the _merge duplicate_ option is the addon's preference otherwise all shared vertices will be merged, included at roads intersection.

Also you can check the _separate object_ option when importing your OSM data, it can help to easier manage your roads.

**Comment by eobet** [comment]
Thank you very much, that solved the issue for me!

Converting the import to curves, extruding and tilting now generates nice, connected road geometry (only thing I'm missing is width information, but perhaps OSM doesn't provide that).
