### ISSUE TITLE
Where is Geoscene panel in Blender 2.82a?

### ISSUE THREAD

**Issue by jimiblender** [domlysz/BlenderGIS#327]
# **Blender 2.82a running on Ubuntu 18.04 LTS** 

I have imported a SHP file using Blender GIS, which I then convert into a terrain layer by creating a Delaunay mesh. I then want to import OSM data (buildings, roads, etc) on the top.
I have attempted to follow the explanation on the Wiki:
https://github.com/domlysz/BlenderGIS/wiki/Georeferencing-management
but I can't actually locate the Geoscene panel anywhere.

I have also attempted to import data via another addon, Blender-OSM, because I couldn't get OSM data to import at all via BlenderGIS.  I understand that the two addons are compatible, but I would like to confirm this is the case.

![Scene info](https://user-images.githubusercontent.com/63593073/80871049-a774cc80-8caa-11ea-8954-00d82c013a3a.png)
I see this information in Properties.

![Blender GIS preferences](https://user-images.githubusercontent.com/63593073/80871058-bce9f680-8caa-11ea-967f-09aa30c12bc4.png)
And this information in Edit-Preferences.

![Geoscene panel from Wiki](https://user-images.githubusercontent.com/63593073/80871214-d93a6300-8cab-11ea-96a3-0f8b27983e3c.png)
However, I cannot find this panel.

# **Error message**

I receive no error messages, I just can't get OSM data imports to coincide with my SHP file import (they appear to be the same scale but are inserted in different places. Without the Geoscene panel I imagine it's impossible to correct this

**Comment by domlysz** [comment]
It's located in the 3dview properties :
![image](https://user-images.githubusercontent.com/5639024/80871487-3387f380-8cad-11ea-9f4a-533b2fa4db73.png)

But it will not solve your issue, firstly because the 2 addons are not compatible at all, and secondly because what you describe is a typical miss alignment due to data in different projection systems. When you import osm data, by default the projection is set to Web Mercator, so if you shapefile is not is this projection too then it will not be aligned. The first step is to determine what is the projection of your shapfile and what is the projection you want to work in Blender.

**Comment by jimiblender** [comment]
Thanks a lot for your help once again! I'll delve into projection systems and see if I can get it to work. In general I find that Google is the only basemap which works for me, even after reinstalling Blender via Snap and reinstalling BlenderGIS, but that's a separate issue maybe.
Cheers.
