### ISSUE TITLE
ERROR:BlenderGIS-master.core.proj.srs:45:Cannot initialize crs

### ISSUE THREAD

**Issue by matslemmens** [domlysz/BlenderGIS#344]
# **Blender and OS versions**

Blenderversion: 2.83 stable version from website blender.org
Windows 10 64bit 
Extra info: I'm behind a proxy

# **Describe the bug**

Blender-GIS will produce some errors in the console even when i'm not using the addon. 
It doesn't interupt the working with Blender, but i presume that one doesn't want something to use cpu-cycles without need...

# **How to Reproduce**
Open Blender
Open the system console.
Import a dxf via the standard blender addon (dxf-importer).
Then you get for the first time the error.
Then everytime i open the view panel in the 3D view (shortcut 'n' - go to 'view'-tab) the error occurs.
If i go to another window in blender

 (for example the blender-text-editor) and go back to the 3D view with the mousecursor, the error gets triggered again. It keeps triggering it this way (when changing focus away and back to 3D viewport), as long as the viewpanel is open. If the viewpanel is not open (because the n-panel has another tab activated) the error doesn't occur. But when you switch back to the viewpanel, it re-occurs.

It doesn't happen with standard objects from blender (cube, suzanne, .... ) 

In the zip you can find a small dxf file plus a video of the occurance and reproducing of the error.
[blenderGIS_dxf_video.zip](https://github.com/domlysz/BlenderGIS/files/4785612/blenderGIS_dxf_video.zip)

# **Error message**

ERROR:BlenderGIS-master.core.proj.srs:45:Cannot initialize crs
Traceback (most recent call last):
  File "C:\Users\lemmenma\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\BlenderGIS-master\core\proj\srs.py", line 42, in validate
    cls(crs)
  File "C:\Users\lemmenma\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\BlenderGIS-master\core\proj\srs.py", line 85, in __init__
    raise ValueError('Invalid CRS : '+crs)
ValueError: Invalid CRS : tmerc
![afbeelding](https://user-images.githubusercontent.com/36260320/84753458-4f2a2d80-afbf-11ea-8240-4c127e96c508.png)
[bgis.log](https://github.com/domlysz/BlenderGIS/files/4785520/bgis.log)

**Comment by domlysz** [comment]
Sound like the dxf addon use the same custom property name for storing the projection of the scene but not in the same way as BlenderGIS. With BlenderGIS the crs must be defined with an EPSG code or a valid proj4 string, so the value _tmerc_ is invalid.

The error appears if the geoscene panel is displayed, because this panel check the validity of the crs and will be red if the test fails

![image](https://user-images.githubusercontent.com/5639024/84793810-d397a300-aff5-11ea-9645-b3380f7006fd.png)


A valid SRID for BlenderGIS look like this and it's conform to the template applied in every gis software

![image](https://user-images.githubusercontent.com/5639024/84793934-f5912580-aff5-11ea-985e-4b0b96106e4d.png)

**Comment by domlysz** [comment]
IMHO tmerc cannot be considered as a valid spatial reference identifier, for exemple the code EPSG:2193 is a valid SRID defining a transverse mercator projection with the following parameters +proj=tmerc +lat_0=0 +lon_0=173 +k=0.9996 +x_0=1600000 +y_0=10000000 +ellps=GRS80. The code EPSG:2157 define another transverse mercator projection with these parameters +proj=tmerc +lat_0=53.5 +lon_0=-8 +k=0.99982 +x_0=600000 +y_0=750000 +ellps=GRS80

Both use the _tmerc_ keyword but are not the same projection at all because they are not centered to the same place. I think the dxf importer missuse the SRID keyword.
