### ISSUE TITLE
Height and Object data not loading correctly

### ISSUE THREAD

**Issue by GentleThud** [domlysz/BlenderGIS#359]
# **Blender and OS versions**

Blender 2.83.1  |  macOS 10.14.6

# **Describe the bug**

Forgive me if this is a double up ... I'm new to Blender and to Blender GIS.

I'm aware that there are limitations on the size of a landscape import in one hit, so I'm trying to assemble a landscape in sections. I'm successfully pulling in the OSM maps and having them automatically geolocate in their correct positions, overlapping them to to avoid gaps. 

However trying to import height info, it keep putting the height data for the original area over each new section, repeating the effect cookie-cutter style. 

And when I select 'Get OSM' to pull in the objects, apart from the first section which geolocates correctly, all the others seem to pile up over that first section and don't locate correctly over the adjacent sections. See screenshot ...
![Screen Shot 2020-07-09 at 15 34 25](https://user-images.githubusercontent.com/68035738/87001885-de5fe500-c1fb-11ea-8d21-3e9d3ad31440.png)

Is this a bug, simply a limitation, or is it user error?

# **How to Reproduce**

- Select Web Geodata > Basemap > then 
![Screen Shot 2020-07-09 at 15 37 06](https://user-images.githubusercontent.com/68035738/87001175-27af3500-c1fa-11ea-98de-d4a66f6b035e.png)
 
- Move map area, from original section, to overlap slightly, without zooming in or out

- Press E to  import

- Select SRTM and OK to import height data

- Select Get OSM to import objects ... I've been selecting all categories, as per screenshot
![Screen Shot 2020-07-09 at 15 48 16](https://user-images.githubusercontent.com/68035738/87001819-a8bafc00-c1fb-11ea-8420-0db72350c887.png)

**Comment by domlysz** [comment]
sound like a workflow issue here, if you want to proceed by chunk like this you have to be careful to be consistent because the current active object define request extent for grabbing SRTM or OSM data. If there is no active object then the current view extent is used. Also, for OSM data you need to carefully choose the object to get the elevation from.

However your workflow is a pain. If you want to grab a larger area with the basemap operator use the L shortcut to lock the view extent (this function is explained in the wiki). Then if the area is too large for OSM or SRTM requests, a better way to go is to download the source dataset (respectively xml and tiff files) through services adapted to large volumes, and then import these datasets with the addon.
