### ISSUE TITLE
Displacement DEM - how to apply the same displacement to different sized planes?

### ISSUE THREAD

**Issue by CharlieTemplar** [domlysz/BlenderGIS#386]
# **Blender and OS versions**

Blender 2.82 Windows 10

# **Describe the bug**

Trying to overlay various map images over a displaced plane and was hoping to apply the the same displacement DEM and leave the semi transparent maps floating over the aerial photo terrain but the overlay maps displace differently.
![image](https://user-images.githubusercontent.com/47461175/93932282-d5b97e00-fd17-11ea-878e-69ca0b1baf89.png)
Tried without smoothing on, but same problem
![image](https://user-images.githubusercontent.com/47461175/93933001-e8808280-fd18-11ea-8a9c-118d64d6f653.png)

Any ideas how to achieve this?  

# **How to Reproduce**

Import 2 images same projection, and overlapping location.  apply displacement DEM

**Comment by domlysz** [comment]
The result depends on how many vertex the displacer can deal with. A large plane will need more subdivison to reach the full DEM resolution. Sometime adding a second subsurf modifier can help.

The other way is to import DEM file as RAW data (it will produce a full resolution mesh) and then apply the map on it. Bellow the flowchart :
![flowchart](https://user-images.githubusercontent.com/5639024/94685979-73213d00-032a-11eb-95e4-5e2583071eaf.jpg)

**Comment by CharlieTemplar** [comment]
well that is quite a procedure, but gets to what I wanted. Thanks
import each georeferenced image as basemap plane
import  DEM raw  clipped to extent for each image
reimport each image as basemap on mesh

I have a problem with the images applied as texture tho. The black offset edge from where the georeference image is projected and slightly rotated, this is alpha masked in the image, but basemap to mesh seems to lose texture position.
![image](https://user-images.githubusercontent.com/47461175/94872141-bc18e480-0443-11eb-9a03-b1fb4d218946.png)
So how can I position this texture properly and mask the black edges?

**Comment by domlysz** [comment]
You should compare the black border size in orthographic top view because the perspective view and the mesh deformation can result on misleading perception.

Alpha channel is always taking into account by Blender, sound like in your image the black border is coded with a special nodata value or maybee in the geotiff mask band, these both approach can't be interpreted natively by Blender. You should preprocess your file to convert nodata values or mask band into the alpha channel.

**Comment by CharlieTemplar** [comment]
I guess the mesh clipped to extent is not clipping to the extents of the image/plane that I create first, but the nearest whole face derivable from the DEM and this results in a mesh which is smaller than the original image/plane.
![image](https://user-images.githubusercontent.com/47461175/95141077-298c8400-0768-11eb-91cc-3dc30ac09097.png)
basemap to mesh maps the image perfectly to geolocation, but because the mesh is in the wrong place/size, it doesn't line up
![image](https://user-images.githubusercontent.com/47461175/95141681-bab02a80-0769-11eb-8a37-a2de220564ea.png)

**Comment by domlysz** [comment]
The cut extent is first rounded to fit the next pixel then the DEM mesh is building by connecting the pixel center, that's why there is an offset of 1/2 pixel.

I'm not sure of what you're trying to do, in the first screenshoot you have a large arial photo and your map above and you want to resolve the relief variation between the 2 meshes, I tell you you just need to densify the subsurf of the aerial photo. Now you want to match the extent of a DEM and a map, I'm sorry I don't understand what's the point. Define your working extent with a plane once for all, then import a DEM or a basemap on it as you want, duplicate the plane as you need.

**Comment by CharlieTemplar** [comment]
I simply want to overlay small small grid maps on to a large aerial photo landscape and rather than them floating flat in mid-air, I am applying the elevation to them so that they sit on the surface.  
I've kind of managed to do it, but I want the whole thing to be semi transparent with the black borders masked but the best I have been able to do is one or the other, but not both....
![image](https://user-images.githubusercontent.com/47461175/95246660-b5f08280-080c-11eb-9bce-349d1624653e.png)

**Comment by domlysz** [comment]
So your question is related on how to use Blender itself : how to setup materials, textures and shaders. I'm sorry it's out of the scope of this issues board, your topic is not valid bug report for the BlenderGIS addon, it's a general question about Blender usage.

**Comment by CharlieTemplar** [comment]
My question from the beginning was how to use blender to work around how blenderGIS imports images.

Adding subsurf did improve the situation but it's impossible to get the divisions to be the same size so you end up with gaps and cpu cost is heavy. 
The alternative method of mesh from raw dem clips smaller than the image so you lose part of the image.

You have explained what blenderGIS is doing and the limitations, so thanks for that. I've been able to partially workaround these problems/limitations and achieved my use case.  If this doesn't qualify as an issue, go ahead and close it.
