### ISSUE TITLE
Elevation Data don't have much detail.

### ISSUE THREAD

**Issue by M-Ibtesam** [domlysz/BlenderGIS#387]
Evaluation Map has low resolution
https://github.com/domlysz/BlenderGIS/issues/289
# **Blender and OS versions**
Blender 2.83
Windows 10 (2004)

# **Describe the bug**
It's not a bug. It's more like a request if you can increase the resolution of the SRTM data map so displacement modifier will be able to add more detail to the mesh.

# **How to Reproduce**
1. just go to the WebGeoData tab
2. generate image texture from any world location
3. then generate SRTM data for it.
4. you will be able to see that elevation isn't much detailed even after adding proper subdivision too.

**Comment by domlysz** [comment]
SRTM data has a resolution of 90m per pixel (30m for the US), the dataset is produced by NASA. Sorry I can't send a spaceship to produce a higher resolution global elevation model for everyone and for free.  If you need better resolution you may search for others datasources for you location of interest, some country provides elevation model as opendata, otherwise you will certainly have to pay it. The addon can import any kind of elevation model in geotiff format.

**Comment by M-Ibtesam** [comment]
Thanks for the reply. Sorry i don't know much about geo location data. Btw,
you addon is awesome. It's a great help :)

**Comment by NoctisC7** [comment]
Google Earth has way much more detail, is it possible to load heighmap from there?
