### ISSUE TITLE
No option for Terrain Area Size

### ISSUE THREAD

**Issue by M-Ibtesam** [domlysz/BlenderGIS#393]
# **Blender and OS versions**
Blender 2.83
Windows 10 (2004)

# **Describe the bug**
First of all, I want to thank you for making such a great plugin.
It's not a bug it's more like a feature request. can you add the property or field to add a specific terrain area size like If I want to Get just the 30-meter area? Right now, It's size and aspect ratio is limited to viewport size and aspect ratio but. can you add the option to choose between viewport or custom size by terrain area in meters? If there could be two custom properties for X and Y  so I can get the exact 30-meter area or what I desire. it would be awesome.
I can change other properties from the custom property area but there is no option for terrain area size (in meters).

# **How to Reproduce**
![Annotation 2020-10-02 022403](https://user-images.githubusercontent.com/26528352/94865243-afea5280-0456-11eb-9a94-df5dd7f56a81.png)

# **Error message**
It's not a bug. it's a feature request.

**Comment by domlysz** [comment]
You can cut the resulting mesh to the desired extent afterward. Not sure what you want to say with "30-meter area", do you want to grab only 30m² ?

**Comment by M-Ibtesam** [comment]
> You can cut the resulting mesh to the desired extent afterward. Not sure what you want to say with "30-meter area", do you want to grab only 30m²?

yes, I want only 30m² for game use.

**Comment by domlysz** [comment]
Units of the map are in meters so you can cut it accuracy, however you may consider the distortions caused by the Web Mercator projection, see [FAQ](https://github.com/domlysz/BlenderGIS/wiki/FAQ#why-my-measurements-on-basemaps-reference-seems-wrong-). Also if you intend to pick SRTM data for relief you will get only one elevation value for the whole area as one SRTM pixel value represent 90m².

I don't think my addon fit your usecase, for this kind of scale what you need is a topographic survey of your area of interest !

**Comment by M-Ibtesam** [comment]
ok, thanks for clearing it
