### ISSUE TITLE
use of SRTM 30 Meteter

### ISSUE THREAD

**Issue by bluelemonade** [domlysz/BlenderGIS#401]
is there a possibility to integrate the SRTM 30 meter data from https://search.earthdata.nasa.gov/? would be great to use this higher resolution data, you would only have to create one user in the protal.

**Comment by domlysz** [comment]
For a long time SRTM 30m was only available for US, that's why I only integrated the version at 90m. But it sound like the situation has changed recently, so I've added a new entry point in the addon predeference for grabbing SRTM 30m from Opentopography web service.

![image](https://user-images.githubusercontent.com/5639024/96968889-ef660500-1511-11eb-8eaa-e69850acdb60.png)
