### ISSUE TITLE
Saving blend file with GeoTIFF as plane and DEM "forgets" settings

### ISSUE THREAD

**Issue by mixedbredie** [domlysz/BlenderGIS#54]
I have an odd problem. I create a new blender project with a GeoTIFF DEM added as plane and then again as DEM. I add a geo-referenced camera and have everything setup to render a lovely hill-shaded image.  If I render the image after saving project and __without closing the project__ I get the expected output.  If I save the project, __close it__ and then __re-open it__ I get a flat grey image without any of the relief.  All the settings are saved as set.  

Any suggestions as to what might be happening here? I have 91 tiles to render and would like to batch process them by setting up the .blend files and letting them run overnight instead of having to manually run each one.

![Image created without closing Blender file](https://cloud.githubusercontent.com/assets/3995787/20934371/c99785ca-bbd2-11e6-9eb2-31ca71c4d001.jpg)
![Image created after saving, closing and re-opening Blender file](https://cloud.githubusercontent.com/assets/3995787/20934390/dbcd1fac-bbd2-11e6-87bf-ad2d0b02f168.jpg)

This happens on both Windows 7 64bit and Linux Mint 18 64bit with the Blender GIS extension added.  Other Blender projects created without using the extension reopen correctly.  I have attached the Blender file that create the first image above: [8_3.zip](https://github.com/domlysz/BlenderGIS/files/634470/8_3.zip)

And the GeoTIFF: [int_tiff.zip](https://github.com/domlysz/BlenderGIS/files/634491/int_tiff.zip)

**Comment by mixedbredie** [comment]
I should add that I am using Blender 2.78a and a recent copy of the BlenderGIS addon on both Windows 7 and Linux Mint 18.

**Comment by domlysz** [comment]
Hi,

Thanks reporting the issue.

When importing a raster coded in 16 bits integer, the script cast the data into a new image coded in float32 (because its a pain to handle negative value of signed 16 bits dataset). 

After the import, in the image editor the datatype is correctly detected as float

![selection_030](https://cloud.githubusercontent.com/assets/5639024/20943148/a07bd386-bbfe-11e6-8ddb-22cc657ee5a4.jpg)

but after reopening the blend file, the image is detected as byte

![selection_031](https://cloud.githubusercontent.com/assets/5639024/20943212/cecc777c-bbfe-11e6-9608-c84a16ae94e9.jpg)

So the problem come from here but can't explain this inconsistency, I need to investigate more

**Comment by mixedbredie** [comment]
I've done a few more tests with the same image but saved as UInt16 and Float32 and in both cases the image is retained as RGBA float when the project is saved, closed and reopened.  So, to solve my problem I can use either Unsigned 16 bit Integer or Float32 GeoTIFFs. This doesn't shed any light on why Signed 16 bit integer GeoTIFFs fail though :-(

**Comment by domlysz** [comment]
Finally found the problem, as i explained before when trying to import signed int16 raster the script cast beforehand the data to float32. This new image is then packed into the blend file but packed image can only be stored as png and this format does not support float32 data, so the image re-converted to 8bits...

Results, I can't use the pack function anymore and I need to modify the script in order to copy the new 32bits image into an external file (in exr format because blender can't write 32bits tiff).

Unfortunately this modification seems more tricky than i expected so for now I think the best workaround is to convert all your raster in uint16 or float32. These 2 datatypes can be correctly used as displacement texture in Blender (there is no need to produce a new image).

**Comment by mixedbredie** [comment]
Thanks @domlysz - my batch process is running as I type using Uint16 GeoTIFF with 4 tiles processed and 87 to go...

**Comment by domlysz** [comment]
fixed
