### ISSUE TITLE
map projection on srtm

### ISSUE THREAD

**Issue by mirlip** [domlysz/BlenderGIS#75]
I couldn't import the SRTM because of a missing tif in /home, but as far as I can see from the commits, UVs are used to reproject maps. Cycles has powerfull nodes for it, which would adapt to topology changes and would avoid using complex UVs. You can use the geometry node 'position' output to project the map and then some math nodes to do the required transformations. Also using the reprojected images (from PIL/GDAL/whatever will make rendering faster)

**Comment by domlysz** [comment]
refactoring branch is under development and the srtm importer is not yet finished, it's just a quick test at early early stage

not sure I can correctly achieve raster reprojection with nodes, I will investigate, however I'm pretty happy with the uvmap trick because it works without gdal, (just need some coordinates transformation on a web server) and its reliable if we add more points with subdivision

**Comment by mirlip** [comment]
Hi domlysz,
early stage is good to discuss design. But I can understand your point of view. I'm happy to follow the development.

**Comment by mirlip** [comment]
@domlysz I'll happy to test and report bugs when SRTM import is ready. I tried today, but only got the cube transformed in a sphere the first time, without any error. The second time an error 500 that the server was not working.
```

TIFFReadDirectory: Warning, Unknown field with tag 34737 (0x87b1) encountered.
[out:xml][bbox:47.60217391727185,10.219131382850745,47.62307849215146,10.281910400887133];(((way[highway];way[waterway];way[building];way[landuse]);>););out;
Overpass query success
Warning: Path 'C:\Users\mirlip\AppData\Local\Temp\blender_a00952\GOOGLE_SAT_WM.tif' cannot be made relative
Warning: Total files 3 | Changed 2 | Failed 1
http://opentopo.sdsc.edu/otr/getdem?demtype=SRTMGL3&west=nan&east=nan&south=nan&north=nan&outputFormat=GTiff
Traceback (most recent call last):
  File "C:\blender\2.78\scripts\addons_extern\BlenderGIS\operators\io_get_srtm.py", line 36, in invoke
    return self.execute(context)#context.window_manager.invoke_props_dialog(self)
  File "C:\blender\2.78\scripts\addons_extern\BlenderGIS\operators\io_get_srtm.py", line 95, in execute
    with urllib.request.urlopen(url) as response, open(filePath, 'wb') as outFile:
  File "C:\blender\2.78\python\lib\urllib\request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "C:\blender\2.78\python\lib\urllib\request.py", line 472, in open
    response = meth(req, response)
  File "C:\blender\2.78\python\lib\urllib\request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\blender\2.78\python\lib\urllib\request.py", line 504, in error
    result = self._call_chain(*args)
  File "C:\blender\2.78\python\lib\urllib\request.py", line 444, in _call_chain
    result = func(*args)
  File "C:\blender\2.78\python\lib\urllib\request.py", line 696, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "C:\blender\2.78\python\lib\urllib\request.py", line 472, in open
    response = meth(req, response)
  File "C:\blender\2.78\python\lib\urllib\request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\blender\2.78\python\lib\urllib\request.py", line 510, in error
    return self._call_chain(*args)
  File "C:\blender\2.78\python\lib\urllib\request.py", line 444, in _call_chain
    result = func(*args)
  File "C:\blender\2.78\python\lib\urllib\request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: Internal Server Error
```

**Comment by domlysz** [comment]
work for me, here the workflow

- start basemaps with google sat and zoom somewhere (zoom 16 for exemple)
- [facultative] to get a more detailled texture at the chosen extent, you can press L to lock the view and zoom one or two step forward
- press E to export the map to a new plane mesh
- press get SRTM button

here an exemple @Navacelles Circus

![image](https://user-images.githubusercontent.com/5639024/27386284-961d658a-5695-11e7-8975-69b4b2e286a1.png)

**Comment by bliblubli** [comment]
just discovered your new branch, works great :) But I get like steps/terraces instead of smooth hiles. It doesn't come from the data as maperitive gives smooth results and also uses the srtm data. 
Look like 2 vertices get their z coord from the same pixel. If it's the case, having each vert at the middle of the pixel/ height texel would maximize quality and ensure smooth topography.

**Comment by mirlip** [comment]
thanks for the workflow, it works great now, problem was that the cube was selected.
Would it be possible to cache the srtm files? Best would be to be able to give a directory with all the srtm files. I also use maperitive a lot and it has a cache folder with all cached srtm tiles. It would save some GB of memory to have both BlenderGIS and maperitive use the same dir.

**Comment by domlysz** [comment]
@bliblubli  thanks for the feeback, I know this problem, it appears when the subdivision level is too high for the extent and give more vertices than necessary for example with SRTM3 each pixel is about 90m, if the subsurf give one vertices each 50m you will have 2 points on the same pixel. For now reducing the subsurf level fix the problem, but I will implement a more useful function to compute ideal subsurf level.

@mrlip actually the tool request the optopo server only for the expected extent, so the resulting image does not follow the SRTM grid and is not really usable in a cache. Make sense for me to pick up only some part of the SRTM instead of storing the huge tiles (its something like 500x500km), furthermore working with tiles will involve some image processing tasks (cut or stich tiles)

**Comment by mirlip** [comment]
@domlysz the advantage of a cache is that it works without internet connection and is faster. When you create the texture with E, it also stitch and cut an extent from the cache. Maybe there is a way to convert the SRTM data to tiled one channel textures that would also be stored like the OSM/Google/Bing maps? It would also allow to create DTM of any size and resolution.

**Comment by mirlip** [comment]
Note that E only works if file is saved. New files give some error about missing bpyIMG or so 
```
#Add new attribute to geoImg class (like GeoRaster class)
setattr(rast, 'bpyImg', bpyImg)
```

**Comment by domlysz** [comment]
seems it happen when the image is under construction (tiles donwload still in progress)

**Comment by domlysz** [comment]
must be fixed now

**Comment by mirlip** [comment]
it works really good now :) thanks for the fix.
