### ISSUE TITLE
Update Install GDAL wiki

### ISSUE THREAD

**Issue by stuarta0** [domlysz/BlenderGIS#91]
I had to jump through an extra hoop whilst getting GDAL to work on windows. On the [How to install GDAL](https://github.com/domlysz/BlenderGIS/wiki/How-to-install-GDAL) wiki page under the windows section you could consider adding this:

In some cases reprojection will fail with the following message in the system console:
```ERROR 4: Unable to open EPSG support file gcs.csv. Try setting the GDAL_DATA environment variable to point to the directory containing EPSG csv files.```

Whilst the blender python statement ```os.environ['GDAL_DATA']``` prints the correct path, it seems the binding requires a Windows environment variable that is missing. Copy the path from the reported path in python and create an equivalent Windows environment variable to solve the issue.

**Comment by onerobotband** [comment]
Ok, figured out installing the WHL. Stuarta0, I don't follow your last paragraph. I tried inputting os.environ['GDAL_DATA'] into the python scripting window and it returns the following:

Exception ignored in: <bound method MAP_VIEWER.__del__ of <bpy_struct, MAP_VIEWER invalid>>
Traceback (most recent call last):
  File "C:\Users\orb\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\BlenderGIS-master\operators\view3d_mapviewer.py", line 576, in __del__
    if getattr(self, 'restart', False):
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\modules\bpy_types.py", line 601, in __getattribute__
    properties = StructRNA.path_resolve(self, "properties")
ReferenceError: StructRNA of type MAP_VIEWER has been removed
Traceback (most recent call last):
  File "<blender_console>", line 1, in <module>
NameError: name 'os' is not defined

>>>

How would I go about copying the reported path (if it returned one) to create an equivalent Windows environment variable?

**Comment by domlysz** [comment]
The WHL is a stand alone GDAL installation, you don't need any other GDAL install like OSGEO4w. The WHL install GDAL in the following directory: ` blender_install_folder\2.7x\python\lib\site-packages\osgeo`, this folder contains binary files (.exe) and a GDAL data (`osgeo/data/gdal`).

In the python console you need to import os module before using it :

```
import os
os.environ['GDAL_DATA']
```

Not sure of what this statement will return, but I think you need at least 2 environment variables
- in `path `variable you need to append  the folder` blender_install_folder\2.7x\python\lib\site-packages\osgeo` because this directory contains exe files
- then add a new `GDAL_DATA `variable pointing the folder `blender_install_folder\2.7x\python\lib\site-packages\osgeo\data\gdal`

tel me if it works

**Comment by onerobotband** [comment]
import os
os.environ['GDAL_DATA']

this returns:
'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\python\\lib\\site-packages\\osgeo\\data\\gdal'

therefore i have created a windows environment variable with the variable name "PythonPathBlenderGdal" with the variable value "C:\Program Files\Blender Foundation\Blender\2.79\python\lib\site-packages\osgeo\data\gdal"

I did this following instructions from:

https://www.katsbits.com/tutorials/blender/pythonpath.php#saving

Not having any success, still returning value 6 and basemap crash

**Comment by onerobotband** [comment]
Ok I renamed the windows environment variable from "PythonPathBlenderGdal" to "GDAL_DATA"

Now the value returned is 0 and basemaps is no longer crashing. I will now try getting this working with a different CRS and if I have success I will write back here a post detailing my installation.

**Comment by domlysz** [comment]
Wiki updated : https://github.com/domlysz/BlenderGIS/wiki/How-to-install-GDAL
